<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

There are three basic ways of storing data:

lists,
NumPy arrays and
dictionaries.

## 1.2 Accessing data from a list (or array)

In [5]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [6]:
py_real_names[0]

'Natasha Romanoff'

In [7]:
py_super_names[0]

'Black Widow'

In [8]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [9]:
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

Data in lists (and arrays) must be accessed using a zero-based index.


## 1.3 Accessing data from a dictionary

In [10]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [11]:
superhero_info["Natasha Romanoff"]

'Black Widow'

Remember that dictionaries have a key-value structure.


In [12]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [13]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [14]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [16]:
len(py_list_2d)
len(np_array_2d)
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [17]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [18]:
py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

Remember that NumPy arrays tolerate only a single type.

## 2.3 Adding a number

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [20]:
np_array + 10

array([11, 12, 13, 14, 15])

In [21]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [22]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [23]:
py_list_1 + py_list_2
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [25]:
py_list*2
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [26]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [27]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [28]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [29]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [30]:
py_list == 3     # Works, but what IS the question?
np_array == 3  
np_array > 3  

array([False, False, False,  True,  True])

In [31]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

## 2.8 Mathematics

In [32]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [33]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

1.4142135623730951

Remember (roughly speaking) an operation on a list works on the whole list. In contrast, an operation on an array works on the individual elements of the array.

# Exercises & Self-Assessment

In [1]:
my_list = [1, 2, 3, 4, 5]
sliced_list = my_list[1:4]  
print(sliced_list)  

# Slicing a numpy array
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
sliced_array = my_array[1:4]  
print(sliced_array) 

[2, 3, 4]
[2 3 4]


## Footnotes