<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [5]:
import numpy as np

In [6]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)
x = py_list  
x[1:6:2]

['b2', 'd4', 'f6']

Remember slicing in Python can be a bit tricky.
If you slice with [i:j], the slice will start at i and end at j-1, giving you a total of j-i elements.

## 1.2 Arrays only | Subsetting by masking

In [7]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

Remember that subsetting by masking only works with NumPy arrays.

In [9]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [10]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [11]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [12]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

Remember:

Always use the Bitwise NOT(~), Bitwise OR(|) and Bitwise AND(&) when combining masks with NumPy.
Always use brackets to clarify what you are asking the mask to do.

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [14]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)
py_list_2d[3]
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [15]:
py_list_2d[3][0]
np_array_2d[3, 0]

'4'

In [16]:
py_list_2d[:3]
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [17]:
py_list_2d[:3][0]
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [18]:
py_list_2d[3:6][0]
np_array_2d[3:6, 0]
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [19]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [20]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x
x=[1]
x+= [2]
x+= [3]
x+= [4]
x
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [21]:
x = [1, 2, 3]
x += [4, 5, 6]
x
x=[1, 2, 3]
x.extend([4, 5, 6])
x
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [22]:
a=(1, 2, 3)     # Define tuple

In [23]:
print(a[0])    # Access data

1


In [24]:
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [25]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes